### PR TITLE
Version 0.3.0

### PR DESCRIPTION
**Pull request by Smile4ever**
I hope you like the new version and consider it for merging.

Added features:
Add intelligent guessing based on URI
Add support for network streams (IceCast) that have a Now Playing
attribute
Add translation support
Add GPL header
Wider window
Search with Google button
Switch artist and title with one click on the button Switch
Song change updates the metadata in Lyrics Finder
Better error messages
Add debug mode
Bugfixes

I worked on this for more than a week and I tested it well (on Linux), while it should also work on any other operating system (please test). I'm also the reporter of bug 14786: https://trac.videolan.org/vlc/ticket/14786

### CODE REVIEW

**Comment by alexxxnf** [comment]
Hi and thank you for your participation!

I tried to run it on Win7 x64. No success. If you don’t have Windows, I’ll take a closer look at your changes a little bit later.

Could you please meanwhile update installation instructions? Now we have more than one file.

**Comment by Smile4ever** [comment]
You're welcome! Are you the original author (besides Jean-Philippe Andre) that hosts the VLC extension here? http://addons.videolan.org/content/show.php/Lyrics+from+lyricsmode.com?content=140696

Sorry, it was a small error in the Windows specific code path. Thats now fixed, so I suggest you try it out :)

I did expand the README with more information on the installation and the usage. Is it good like that?

**Comment by alexxxnf** [comment]
I’m not the original author. I don’t have access to the plugin hosted on addons.videolan.org.

Now it works. Looks great! The README looks nice too :)

**Comment by Smile4ever** [comment]
I contacted the original author. If he replies to my message, I will let you know. More translation files for Lyrics Finder are incoming in the next few days. (being worked on is Spanish, German and French)

I see you are Russian, maybe you could create the Russian translation?

1. Sign up here: https://www.transifex.com/signup/
2. Translate here: https://www.transifex.com/projects/p/vlc-lyrics-finder/translate/#ru_RU

**Pull request merged**
